### ISSUE TITLE
Regarding the mapping of the cstick and rumble

### ISSUE THREAD

**Issue by Birutath** [revvv/Nintendont-XBOX360#1]
here in my x360 controller the cstick is inverted between left and right, and rumble doesn't work in neither endpointouts. Maybe gamepad version diferences? (mine is the black slim x360 controller)

**Comment by revvv** [comment]
Yes, I have inverted the x axis by intention for Super Mario Sunshine. Maybe I should have added a configuration option.
https://github.com/revvv/Nintendont-XBOX360/blob/a9164a86ff47291bd7555334e47840d00ed6bfb3/kernel/HID.c#L932

For the moment, you could check if your game provides a configuration option...

Regarding the rumble feature: Looks like your controller requires a different endpoint.
You could try lsmod on Linux to find out the parameter. Or post the output here.

**Comment by revvv** [comment]
Published new release: Added configuration options to invert all axes.
If you send me the lsmod output for your controller I could check why rumble isn't working.
