### ISSUE TITLE
gc game support via usb?

### ISSUE THREAD

**Issue by spielvan** [revvv/Nintendont-XBOX360#10]
It would be interesting, to have support for the games by usb.

**Comment by jjct1** [comment]
Same issue, it will read games from the SD card but not a USB.  The original version I have installed will read from both SD and USB.

**Comment by revvv** [comment]
That's a general problem with USB mass storage devices and XBOX360 controller. Depending on the USB library it might work. For Nintendont's ioctl approach it doesn't.

Sorry for my late answer. github still does not send an email notification for issues.

**Comment by spielvan** [comment]
> That's a general problem with USB mass storage devices and XBOX360 controller. Depending on the USB library it might work. For Nintendont's ioctl approach it doesn't.
> 
> Sorry for my late answer. github still does not send an email notification for issues.

thank you very much for your attention, a pity because it would be a hand in the wheel for the Wii family edition, without even needing to have an sd card and just to add I tested the retro receive mini nes from 8bitdo + ps3 controller with this Nintendont Port and the controller worked perfectly of ps3 fii, with Nintendont thinking it was an Xbox 360 controller.
