### ISSUE TITLE
when connecting controller, it flashes and does nothing else

### ISSUE THREAD

**Issue by vondirge33** [revvv/Nintendont-XBOX360#13]
It works perfectly on my pc, but on nintendont the X button just blinks a bit and turns off.

I tried the possible solutions in the readme, but it doesn't work.

**Comment by revvv** [comment]
Which controller do you have? Only XBOX360 wired version is supported (VID=0x045e, PID=0x028e)

**Comment by vondirge33** [comment]
that's the one i have.  I even checked in the Nintendont hid config wizard that the configuration file generated by that program (045e_028e.ini) matches the one included in the Controllers folder of Nintendont-XBOX360

**Comment by revvv** [comment]
Please provide a log file ndebug.log

**Comment by revvv** [comment]
Closing, because of inactivity.
