### ISSUE TITLE
USB FAT device could not be opened

### ISSUE THREAD

**Issue by PedroRafael215** [revvv/Nintendont-XBOX360#14]
i cant load games from usb. It shows "USB FAT device could not be opened" in red at the top of screen.
Any hints?

**Comment by felipecbritto** [comment]
Same here.

**Comment by PedroRafael215** [comment]
At least booting from disk is possible.Playing burned dvd works.  
I'm wondering to buy a new sd card just to test if it loads from sd too.
I wonder why original build of Nintendont don't see this project and implement it there.
I was really amazed to see my usb xbox360 controller working on it.

**Comment by felipecbritto** [comment]
SD works fine.

**Comment by revvv** [comment]
Sorry for my late answer, but github does not always send me an e-mail.

Unfortunately this is not fixable. Duplicate of #4
