### ISSUE TITLE
Is third party xbox 360 controller VOYEE compatible?

### ISSUE THREAD

**Issue by Sebgames** [revvv/Nintendont-XBOX360#17]
I had previously asked this question, but it was canceled due to inactivity.
when trying retrodetest it does not recognize it but when disconnecting and connecting I managed to get it to be recognized halfway but it only identifies the large button in the middle and when testing rumble or next led the screen freezes

**Comment by revvv** [comment]
Well, then your controller is not really a clone and is not supported. Duplicate of #15

**Comment by Sebgames** [comment]
and there is no way to make it work with some modification or adapter or something like that

**Comment by revvv** [comment]
No
