### ISSUE TITLE
360 Guide button lights reverts from player 1 to constantly flashing all 4 lights after about a minute when a classic controller is connected

### ISSUE THREAD

**Issue by NintendoManiac64** [revvv/Nintendont-XBOX360#18]
Tested with Mario Kart Double Dash and a completely stock copy of USB Loader GX r1281 (albeit with memory card emulation disabled).

Simply put, if you have a wii remote also connected with a classic controller as player 2, the 360 guide button lights will revert from player 1 to flashing all 4 lights after a minute or so (you may or may not need to push a button on the classic controller; I originally had it occur immediately when pressing a button on the classic controller but later had the issue occur purely on its own before I had even pushed a button on the classic controller.)

I don't know if it means anything, but I had to use `EndpointOut=2` despite this being one of the most original OEM wired 360 controllers assuming they underwent multiple revisions (read: it was purchased from *Circuit City*, I believe somewhere around 2006 or 2007?)

**Comment by revvv** [comment]
Interesting, but I fear I can't do anything to fix. Nevertheless the controller works...
