### ISSUE TITLE
[Question] Is the LB button mapped to anything by default?

### ISSUE THREAD

**Issue by NintendoManiac64** [revvv/Nintendont-XBOX360#19]
I'm just wondering if the LB button is mapped to anything in the default configuration?

If not, then it might be a good idea to have the LB double as copy of the GC_Y button because, on a 360 controller, it's nearly impossible to press GC_A+GC_Y (360_B+360_X) at the same time without also pressing GC_X (360_Y) and/or GC_B (360_A).

Metroid Prime／2's GC_A+GC_Y beam combos are probably the easiest example of this.

**Comment by revvv** [comment]
Maybe this could help you:

>  _From Nintendont-XBOX360 README_
> * If the button layout is not perfect, try L+Back to turn buttons quarter clockwise. (Nintendont feature.)

**Comment by revvv** [comment]
And of course you can do a re-mapping in [045e_028e.ini](https://github.com/revvv/Nintendont-XBOX360/blob/master/controllerconfigs/045e_028e.ini) for the unused L and R buttons. Luckily I have added a comment with the values.
