### ISSUE TITLE
Arcade stick xbox 360

### ISSUE THREAD

**Issue by Masana1** [revvv/Nintendont-XBOX360#2]
Hello and thank you for your work on nintendont, I own an xbox 360 arcade stick and I would like to know if it is possible to make Nintendont compatible with this one. I dream of playing snk vs capcom 2 with se stick.

![image](https://user-images.githubusercontent.com/39405785/118521470-5ca1e780-b73b-11eb-8e16-ec4986dc0432.png)

**Comment by revvv** [comment]
A Google search says that VID=0x045E and PID=0x0202.

Checking the Linux sources shows that there are significant differences to the default XBOX360 controller:
https://github.com/torvalds/linux/blob/ea4424be16887a37735d6550cfd0611528dbe5d9/drivers/input/joystick/xpad.c
