### ISSUE TITLE
Support Wii remote by itself as a controller?

### ISSUE THREAD

**Issue by NintendoManiac64** [revvv/Nintendont-XBOX360#3]
As we all know, the dpad on the OEM 360 controller is... not great.  Worse still is that the dpad on the OEM GameCube controller is _also_ not great!

Now normally the ideal solution would be to use a classic controller, but availability of those is lacking nowadays, especially if you're trying to set up a multiplayer gaming session (immense demand for the Super NES classic probably didn't help), and the few games that are d-pad heavy such as Nintendo Puzzle Collection (which itself is also a Japan-only game, so it's all the more likely to be ran via something like Nintendont - especially when using an fan-made English translation) could easily work with nothing more than a sideways Wii remote.

I suppose a Playstation controller could also work, but it was my impression that Nintendont only supports having a single USB controller for player 1 just like Xbox 360 controller support.

Also for reference, Puyo Pop Fever as well as Bust-A-Move 3000 (the PAL version was called "Super Bust-A-Move All-Stars") are two other games in addition to Nintendo Puzzle Collection that are very dpad-heavy yet have minimal button requirements quanity-wise, making them additional good examples of where using only a sideways Wii remote makes sense.

My personal ideal button configuration would be the following (Wii on left, GC on right):
A = R
B = L
1 = B
2 = A
plus = Start
minus = Y
Dpad with remote held sideways = Dpad with controller held normally

**Comment by revvv** [comment]
You can change the button configuration in-game:
https://gbatemp.net/threads/nintendont.349258/

Look for ``Wiimote+Nunchuk button mapping``. Maybe there is a button layout which fits your needs.
