### ISSUE TITLE
"No FAT device found!"  Does this only support SD cards, not USB HDDs?

### ISSUE THREAD

**Issue by NintendoManiac64** [revvv/Nintendont-XBOX360#4]
My friend's Wii (not Wii U) is set up with only a USB drive which worked fine for Devolution and vanilla Nintendont, but when I replace the boot.dol for vanilla Nintendont with your modified boot.dol, I get a "No FAT device found!" whenever I try to boot a game.

This error occurs regardless of whether I boot it through USB Loader GX, directly via the Homebrew Channel, with the 360 controller plugged in, or with the 360 controller not plugged in.  It similarly occurs regardless of which USB port the USB HDD is connected to (though only the Homebrew Channel is able to launch Nintendont via either USB port; USB Loader GX only supports loading games from the lower USB port).

I tried enabling debug and logging in USB Loader GX but, AFAICT, no log was created (possibly because Nintendont couldn't find a FAT device to save the log to).

----------------

If it makes any difference, I'm using the same 360 controller that I originally tested with back when you initially mentioned to me that you made a fork of Nintendont implementing 360 controller support (at the time of which I tested on my own Wii running a game from an SD card): https://github.com/FIX94/Nintendont/issues/804

This same 360 controller also works in both Snes9x and Devolution.

**Comment by revvv** [comment]
Yes, launching games from USB could be a problem. I have not tested it, because I always use an SD card.
I know that the XBOX controller on the Wii causes such problems and there is probably no workaround.
I'm not even sure if trying another USB drive might help...

**Comment by NintendoManiac64** [comment]
I probably should have been clearer in my original posting that Snes9X GX, which is also open source and supports the wired 360 controller, works even when Snes9X GX is ran through USB and is accessing ROMs from USB.

**Comment by revvv** [comment]
Snes9X GX uses the official USB API (usb.h). Nintendont doesn’t use it or cannot use it, because there is not enough space. So USB is done directly with ioctls and obviously something is missing that usb.h does…
