### ISSUE TITLE
Does Nintendont-Xbox360 have compatibility with xbox 360 controller to usb adapter?

### ISSUE THREAD

**Issue by Latiascringesatyou** [revvv/Nintendont-XBOX360#5]
So I have two xbox 360 controllers, one of which needs that to-usb adapter thing to connect to the wii's usb port. The one without the usb adapter works perfectly on my wii, but the one that needs it doesn't. I quickly guessed that it was the adapter's fault, but if so I was asking if you could, I don't know, add support for the adapter? Please answer quickly my brother really wants to play mario sunshine and he'll start assuming things

**Comment by revvv** [comment]
What kind of USB adapter are you using? Is it the dongle for a wireless controller?
I'm sorry, but this doesn't work. Some testers said that it crashes badly...
