### ISSUE TITLE
Booting from USB Loader GX not working

### ISSUE THREAD

**Issue by soniccd123** [revvv/Nintendont-XBOX360#7]
I noticed that when loading GC games from USB Loader GX (r1272) with the Xbox 360 controller connected, it freezes in a black screen. If I load Nintendont from the HB channel, with the controller connected, it works like a charm, I'm using Nintendont-XBOX360 v1.3. Also, controller connected to USB port 1, games on SD card. If I load GC games from USB Loader without the Xbox 360 controller connect, it works normally

Thanks, awesome project anyway!

**Comment by revvv** [comment]
Indeed, the XBOX360 controller causes USB problems. My theory is that it responds to USB drive requests and this results in a crash.
