### ISSUE TITLE
about inverted controls

### ISSUE THREAD

**Issue by Ziad09** [revvv/Nintendont-XBOX360#8]
i started super mario sunshine and the controller worked but the y axis on the left analogue was inverted 
how can i change that and future problems like this ?
i tried diffrent ports and its still the same for some odd reason just the y axis on the left stick is inverted
tried the controller on pc and it worked just fine

**Comment by revvv** [comment]
Without checking… IIRC the left stick moves the character. For me it works fine. The right stick for the camera indeed is inverted, but this was the original game, too. Both sticks can be configured. Look in the controller.ini file.
