### ISSUE TITLE
Xbox 360 controller support in upstream

### ISSUE THREAD

**Issue by JayFoxRox** [revvv/Nintendont-XBOX360#9]
Xbox 360 controller support is great, however, I'd like to see this feature upstream, so it's easier to update nintendont through auto-update + use existing frontends like WiiFlow Lite (which expects nintendont in a specific folder presumably).

*(Also, upstreaming is good in general, to avoid community fragmentation)*

---

Any plans for this?

**Comment by revvv** [comment]
To support USB and XBOX360 controller at the same time, you need to rework the code.
And then there might be problems with USB mass storage devices, because they respond to the XBOX360 lookup request.

Sorry for my late answer. github still does not send an email notification for issues.
